sudo: false
language: node_js
node_js:
- '6'
branches:
  only:
  - master
before_script:
  - yarn pull_airtable
before_deploy:
  - yarn build
cache:
  yarn: true
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PERSONAL_ACCESS_TOKEN
  local_dir: dist/
  keep-history: true
  on:
    branch: master

