sudo: false
language: node_js
node_js:
  - '9'
branches:
  only:
  - master
env:
  global:
    - secure: "NEMZOnQr++vM6ZibnCjukL9duIGKZQy6x/pRx3Yo424qfzPO+3GomdekCmL+YBfg5OlS9PaDWMYQWmZk0zE2yo8JmjITauZjjBp/e29ASc1WIkt6BCPSpejf5NPhYVkU6xzLsl8SxtSyOAWtAP2aY20Hjx3mBczLkh2rkp9ryD6I9PdQWaGvhXRQgcmzFLocyQxYVC5OJSCDkMwC7omORnUAp0adVBwFsF3ETBmEH/ZSkM1JdlTGurtx266Lbekb3hd4MS2dSmxpzD8NvN40M2y2n+Xr35g+VRuwoS5HTMlOeHh4y9Wio160lwNSxbOC2fNnM2RNALfGj5lSBSbcMHb3U/W5LxuZFb8ppCDul3OsFRgWoRs9K4I0CWaY1akh5Aju71Dya1waJV4IynAOcch68M6xLA3ZcVwVVvfsdCUsnCnYH5gV/CWNclNDjgMglOgKjvulOTJ5xmxgw8EXJTtGnmJsdhOu6z94g+wfFV7vOG36P0Q+gBC29jtLtrXNAigOHH2rNcElCFs0dbt39WJ9YvyBJymHx/+SaMA1qpykT2W3m5w1EqzkZzBc6n+ucGAc5amDD+h2mdWt0qjpwsZ6MpQSXSFTOqRj1MhbvpIPsfqxRgsUXSWv1qYmvyH0sBB5vK3MGUIZl0oygNVEo/yM/eKuOGKdZAzO9GnL8V4="
before_deploy:
  - yarn build
cache:
  yarn: true
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PERSONAL_ACCESS_TOKEN
  local_dir: dist/
  keep-history: false
  on:
    branch: master
after_deploy:
  - chmod +x ./after_deploy.sh
  - "./after_deploy.sh"
